FROM ghcr.io/graalvm/native-image:ol8-java17-22 AS builder

RUN microdnf install -y findutils

COPY . .

RUN ./gradlew nativeCompile -Pnative

FROM debian:stable-slim

EXPOSE 8080

COPY --from=builder /app/build/native/nativeCompile/rtd-ms-payment-instrumnet .

ENTRYPOINT ["./rtd-ms-payment-instrumnet"]