logging:
  level:
    root: INFO

management:
  info.defaults.enabled: false
  endpoints.enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  defaults:
    metrics:
      export:
        enabled: false